### ISSUE TITLE
Feature Request: OIDC Support

### ISSUE THREAD

**Issue by royaltongue** [oss-apps/split-pro#148]
Instead of having to use just Google, it would be nice to use Authentik, Authlia, etc

**Comment by imnotjames** [comment]
I would like this so I am opening a draft PR.  It's not tested yet - nor does it have any tests written.  I'll try to clean it up and validate it over the next couple of days.

**Comment by Injabie3** [comment]
I can't speak for Authelia, but v1.3.4 works with Authentik. I had to:
- Pass in the following environment variables:
    - `AUTHENTIK_ID` (client ID from Authentik)
    - `AUTHENTIK_SECRET` (client secret from Authentik)
    - `AUTHENTIK_ISSUER` (OpenID Configuration Issuer from Authentik).
- Set the callback URL to `https://yoursplitpro.domain/api/auth/callback/authentik` in Authentik

**Comment by imnotjames** [comment]
Did you pass in the authentic provider to the list of providers?

**Comment by bsncubed** [comment]
I have just gotten Authelia 4.38.7 to work with the Authentik option. Int this example, auth.example.com is authelia, and split.example.com is Split-Pro. This is also running via nginx-proxy-manager, so the docker compose file needs a slight adjustment too. The login option on the webgui does still say Authentik though

docker-compose.yaml
```
...
    ports:
      - 8009:${PORT:-3000}
    environment:
      - PORT=${PORT:-3000}
...
```

.env config
```
PORT=443
NEXTAUTH_URL="https://split.example.com"
AUTHENTIK_ID=split-pro
AUTHENTIK_SECRET=<jwt secret goes here>
AUTHENTIK_ISSUER=https://auth.example.com
```

Authelia OIDC config
```
     - client_id: 'split-pro'
        client_name: 'Split-Pro'
        client_secret: '<jwt digest goes here>'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://split.example.com/api/auth/callback/authentik'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
```
