### ISSUE TITLE
No Login Menu

### ISSUE THREAD

**Issue by ivanzgroot** [oss-apps/split-pro#173]
First of all I find the project amazing and would like to thank the creator for the great work. Now to the problem I am encountering:
I have setup SplitPro via docker-compose like so:

`name: split-pro-prod

services:
  postgres:
    image: postgres:16
    container_name: splitpro-db-prod
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  splitpro:
    image: ossapps/splitpro:latest
    container_name: splitpro
    restart: always
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    environment:
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL:?err}
      - NEXTAUTH_URL=${NEXTAUTH_URL:?err}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - ENABLE_SENDING_INVITES=${ENABLE_SENDING_INVITES:?err}
      - FROM_EMAIL=${FROM_EMAIL}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTHENTIK_ID=${AUTHENTIK_ID}
      - AUTHENTIK_SECRET=${AUTHENTIK_SECRET}
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - R2_BUCKET=${R2_BUCKET}
      - R2_URL=${R2_URL}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - WEB_PUSH_PRIVATE_KEY=${WEB_PUSH_PRIVATE_KEY}
      - WEB_PUSH_PUBLIC_KEY=${WEB_PUSH_PUBLIC_KEY}
      - WEB_PUSH_EMAIL=${WEB_PUSH_EMAIL}
      - FEEDBACK_EMAIL=${FEEDBACK_EMAIL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  database:
`

I would like to be able to access only via E-Mail and not using any OAuth Providers so I have setup following variables:

`POSTGRES_USER="dbuser"
POSTGRES_PASSWORD="censoredpw"
POSTGRES_DB="splitprodb"
DATABASE_URL="postgresql://dbuser:censoredpw@splitpro-db-prod:5432/splitprodb"
NEXTAUTH_SECRET="censored secret"
NEXTAUTH_URL="http://localhost:3000"
ENABLE_SENDING_INVITES=true
FROM_EMAIL=cernsoredemail
EMAIL_SERVER_HOST=smtp.gmail.com
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER=censoredemail
EMAIL_SERVER_PASSWORD=censoredemailapppw`

strangely everything runs when I start the stack via portainer but I don't get a login menu: 

<img width="537" alt="Image" src="https://github.com/user-attachments/assets/98b80a0f-57a6-4fd1-9ae1-bf93e124dc52" />

My first idea was to try and see if I can curl the login so I ran following command:

`curl http\://localhost\:3000/api/auth/providers`

and this was the output:

`{"email":{"id":"email","name":"Email","type":"email","signinUrl":"http://localhost:3000/api/auth/signin/email","callbackUrl":"http://localhost:3000/api/auth/callback/email"}}`

I tried interpreting the curl output and I think it hints that the email provider is configured correctly in the NextAuth setup. So I am a little confused at the moment and don't now what else to try. 

Any help would be appreciated. Thank you in advance.

**Comment by ivanzgroot** [comment]
So the Problem solved itself as soon as I setup a Cloudflare tunnel and modified NEXTAUTH_URL to "https://myurl.com/" 
I then added :
NEXTAUTH_URL_INTERNAL="http://localhost:3000/"
and it started working.
I was able to use the magic link function for my account and got the token via e-mail. 
Now is where the other problem started: 
I tried adding two friends via the add new expense tab and everything seemed ok, also the logs showed email sent. But they never get the email. If I log out and back in from my account I receive the token no problem so it shouldn't be SMTP.
The new users show in the Postgress database but there is no verification date.

**Comment by royaltongue** [comment]
What value goes in `AUTHENTIK_ID`?

**Comment by ivanzgroot** [comment]
I haven't setup any OAuth methods just the SMTP server so that Magic Links are the only way to login. 
All variables that aren't required and aren't related to SMTP have been uncommented in my .env file

**Comment by KMKoushik** [comment]
@ivanzgroot so you have smtp working right. if the log shows mail sent and user did not recieve it, it might be end up in spam.

can you try testing sending invites to your email itself? `youremail+1@gmail.com` like this

**Comment by ivanzgroot** [comment]
The E-mail isn't ending in spam, this is the first thing we all checked. I explained how we got it to work on  #172. But I can't understand what the problem was. The logs always showed the email as sent.

**Comment by imnotjames** [comment]
> The E-mail isn't ending in spam, this is the first thing we all checked. I explained how we got it to work on [#172](https://github.com/oss-apps/split-pro/issues/172). But I can't understand what the problem was. The logs always showed the email as sent.

If you're using Google SMTP does it show as sent from the account you sent from?

**Comment by royaltongue** [comment]
Also getting a blank login screen

My `docker-compose.yml`:
```
services:
##################################################################
##################################################################
##################################################################
  splitpro:
    depends_on:
      splitpro-postgres:
        condition: service_healthy
    container_name: splitpro
    image: ossapps/splitpro:latest
    environment:
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL:?err}
      - NEXTAUTH_URL=${NEXTAUTH_URL:?err}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - ENABLE_SENDING_INVITES=${ENABLE_SENDING_INVITES:?err}
      - AUTHENTIK_ID=${AUTHENTIK_ID}
      - AUTHENTIK_SECRET=${AUTHENTIK_SECRET}
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
    hostname: splitpro
    networks:
      - splitpro
      - caddy_local
    restart: unless-stopped
#################################
  splitpro-postgres:
    container_name: splitpro-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    volumes:
      - ${dcs}/splitpro-related/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    hostname: splitpro-postgres
    networks:
      - splitpro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - diun.enable=false
    restart: unless-stopped
##################################################################
##################################################################
##################################################################
networks:
  caddy_local:
    external: true
  splitpro:
    name: splitpro
```

And my `.env`:
```
domain=[redacted]
dcs=/srv/dev-disk-by-uuid-ca6f47d3-cd3d-4acc-bb5c-53a1d0eb27e5/DockerContainerStorage
pool=/srv/mergerfs/mergerfspool
TZ=America/New_York
##################################################################
##################################################################
##################################################################
# When adding additional environment variables, the schema in "/src/env.js"
# should be updated accordingly.

#********* REQUIRED ENV VARS *********

# Prisma
# DataBase ENV VARS
# You could give a DB URL or give the username, password, host, port individually
# https://www.prisma.io/docs/reference/database-reference/connection-urls#env
DATABASE_URL="postgresql://postgres:[redacted]@splitpro-postgres:5432/splitpro"

# These variables are also used by docker compose in compose.yml to name the container
# and initialise postgres with default username, password
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="[redacted]"
POSTGRES_DB="splitpro"

# Next Auth
# You can generate a new secret on the command line with:
# openssl rand -base64 32
# https://next-auth.js.org/configuration/options#secret
NEXTAUTH_SECRET="Sy6ivfPnvOVN[redacted]1bcr7ocrhs0SRO8eqauE="
NEXTAUTH_URL="https://split.int.deerfox.top"

# Enable sending invites
ENABLE_SENDING_INVITES=false
#********* END OF REQUIRED ENV VARS *********


#********* OPTIONAL ENV VARS *********
# SMTP options
FROM_EMAIL=[redacted]
EMAIL_SERVER_HOST=smtp.gmail.com
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER=[redacted]
EMAIL_SERVER_PASSWORD=[redacted]

# Google Provider : https://next-auth.js.org/providers/google
#GOOGLE_CLIENT_ID=
#GOOGLE_CLIENT_SECRET=

# Authentic Providder : https://next-auth.js.org/providers/authentik
# Issuer: should include the slug without a trailing slash – e.g., https://my-authentik-domain.com/application/o/splitpro
AUTHENTIK_ID=E8b5DvbpjprWF[redacted]sgAVwlNdLIfO
AUTHENTIK_SECRET=ZTOSl2ILV9joak5gauT[redacted]btoq5RkGYntGd2lKKtfFF7q4EHnLr1[redacted]qgPum0aJtsGH3N0Xy88YK
AUTHENTIK_ISSUER=https://auth.[redacted]/application/o/splitpro

# Push notification, Web Push: https://www.npmjs.com/package/web-push
# generate web push keys using this command: web-push generate-vapid-keys --json
#WEB_PUSH_PRIVATE_KEY=
#WEB_PUSH_PUBLIC_KEY=
#WEB_PUSH_EMAIL=

# Email options
#FEEDBACK_EMAIL=

#********* END OF OPTIONAL ENV VARS *********
