### ISSUE TITLE
Login not working/freeze at Validating auth env

### ISSUE THREAD

**Issue by Meister177** [oss-apps/split-pro#184]
I tried setting up the docker compose and env files.

compose
```YAML
name: split-pro-prod

services:
  postgres:
    image: postgres:16
    container_name: splitpro-db-prod
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5123:5432"
    volumes:
      - ${SP_STORAGE}/database:/var/lib/postgresql/data

  splitpro:
    image: ossapps/splitpro:latest
    container_name: splitpro
    restart: always
    ports:
      - ${SP_PORT:-3000}:${SP_PORT:-3000}
    environment:
      - PORT=${SP_PORT:-3000}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@192.168.178.185:5123/${POSTGRES_DB}
      - NEXTAUTH_URL=${NEXTAUTH_URL:?err}
      - NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL:?err}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - AUTH_PROVIDERS=${AUTH_PROVIDERS:?err}
      - ENABLE_SENDING_INVITES=${ENABLE_SENDING_INVITES:?err}
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    name: splitpro_net
```

env
```Properties
SP_PORT=3123
AUTH_PROVIDERS=EMAIL
NEXTAUTH_SECRET="SECRET"
NEXTAUTH_URL=http://192.168.178.185:3123
ENABLE_SENDING_INVITES=false

POSTGRES_USER=split
POSTGRES_PASSWORD="SECRET"
POSTGRES_DB=split
```

After visiting the website this is the console output
```bash
splitpro-db-prod  | 2025-02-07 17:05:24.358 UTC [1] LOG:  database system is ready to accept connections
splitpro          | + echo 'Deploying prisma migrations'
splitpro          | + pnpx prisma migrate deploy --schema ./prisma/schema.prisma
splitpro          | Deploying prisma migrations
splitpro          | Progress: resolved 1, reused 0, downloaded 0, added 0
splitpro          | Progress: resolved 6, reused 0, downloaded 3, added 0
splitpro          | Packages: +6
splitpro          | ++++++
splitpro          | Progress: resolved 7, reused 0, downloaded 6, added 6, done
splitpro          | .../node_modules/@prisma/engines postinstall$ node scripts/postinstall.js
splitpro          | .../node_modules/@prisma/engines postinstall: Done
splitpro          | .../prisma@6.3.1/node_modules/prisma preinstall$ node scripts/preinstall-entry.js
splitpro          | .../prisma@6.3.1/node_modules/prisma preinstall: Done
splitpro          | Prisma schema loaded from prisma/schema.prisma
splitpro          | Datasource "db": PostgreSQL database "split", schema "public" at "192.168.178.185:5123"
splitpro          |
splitpro          | 7 migrations found in prisma/migrations
splitpro          |
splitpro          |
splitpro          | No pending migrations to apply.
splitpro          | Starting web server
splitpro          | + echo 'Starting web server'
splitpro          | + node server.js
splitpro          |    ▲ Next.js 14.1.0
splitpro          |    - Local:        http://...
splitpro          |    - Network:      http://...
splitpro          |
splitpro          |  ✓ Ready in 273ms
splitpro          | Registering instrumentation
splitpro          | Validating auth env
```

And all I see after clicking on "Add Expense" is this

![Image](https://github.com/user-attachments/assets/f249352d-b0f6-4583-b3c1-f3a21083f76a)

Would be nice if someone can help me with this. Thanks :)
