### ISSUE TITLE
Add option to disable new email signups

### ISSUE THREAD

**Issue by lucasnasc2** [oss-apps/split-pro#236]
Hey guys, i'm self hosting splitpro and i can not make the magic link function go away. I have just updated to 1.3.6. I have tried setting the ENABLE_SENDING_INVITES to false, to err or commenting it out entirely and the magic link still works, people can still send themselves emails to join the platform: my docker compose rn looks like this:
```yaml
networks:
  backend:
    driver: bridge
  proxy:
    external: true
services:
  postgres:
    image: postgres:16
    container_name: splitpro-db-prod
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  splitpro:
    image: ossapps/splitpro:latest
    container_name: splitpro
    restart: always
#    ports:
#      - ${PORT:-3000}:${PORT:-3000}
    networks:
      - backend
      - proxy
    environment:
      - HOSTNAME=0.0.0.0
#      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL:?err}
      - NEXTAUTH_URL=${NEXTAUTH_URL:?err}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
#      - ENABLE_SENDING_INVITES=${ENABLE_SENDING_INVITES:?err}
      - FROM_EMAIL=${FROM_EMAIL}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
#      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTHENTIK_ID=${AUTHENTIK_ID}
      - AUTHENTIK_SECRET=${AUTHENTIK_SECRET}
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
#      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
#      - R2_SECRET_KEY=${R2_SECRET_KEY}
#      - R2_BUCKET=${R2_BUCKET}
#      - R2_URL=${R2_URL}
#      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - WEB_PUSH_PRIVATE_KEY=${WEB_PUSH_PRIVATE_KEY}
      - WEB_PUSH_PUBLIC_KEY=${WEB_PUSH_PUBLIC_KEY}
      - WEB_PUSH_EMAIL=${WEB_PUSH_EMAIL}
#      - FEEDBACK_EMAIL=${FEEDBACK_EMAIL}
#      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    depends_on:
      postgres:
        condition: service_healthy
```
The expected behavior is the magic link interface still appear, but not work due to the .env variable. But it still works.

_Originally posted by @lucasnasc2 in https://github.com/oss-apps/split-pro/issues/176#issuecomment-2926254297_

UPDATE: Okay, i have looked at the code in the mailer.ts file and i have found that the function responsible for the sign-up email has nothing to do with the ENABLE_SENDING_INVITES variable.
So, i think this is actually simpler than i had thought. The function sendSignUpEmail should be enhanced with an environment variable check like ENABLE_OTP_SIGNUP or something like that. Maybe even some sort of ACL where you can only send invitation emails to people on your domain (e.g. only send the signup email to people with @MySplitproDomain.com).
This might be part issue and part feature request. Issue because it's a security problem to have the whole world accessing the page if you're self-hosting and feature request regarding the ACL.

The following code is a dirty example:

```javascript
export async function sendSignUpEmail(email: string, token: string, url: string) {
  const { host } = new URL(url);

  console.log(env.NODE_ENV);

  if (env.NODE_ENV === 'development') {
    console.log('Sign in link : ', email, url, token);
    return true;
  }

  if (!env.ENABLE_OTP_SIGNUP) {
    throw new Error('Email login is not enabled');
  }

  const subject = 'Sign in to SplitPro';
  const text = `Hey,\n\nYou can sign in to SplitPro by clicking the below URL:\n${url}\n\nYou can also use this OTP: ${token}\n\nThanks,\nSplitPro Team`;
  const html = `<p>Hey,</p> <p>You can sign in to SplitPro by clicking the below URL:</p><p><a href="${url}">Sign in to ${host}</a></p><p>You can also use this OTP: <b>${token}</b></p><br /><br /><p>Thanks,</p><br/>SplitPro Team</p>`;

  return await sendMail(email, subject, text, html);
}
```
